# Generated by Django 5.2.6 on 2025-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Undeclared', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
