# Generated by Django 5.2.6 on 2025-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
