# Generated by Django 5.2.6 on 2025-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('relation', models.CharField(max_length=20)),
            ],
        ),
    ]
