# Generated by Django 5.2.6 on 2025-09-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.emergencynumber'),
        ),
    ]
